# Copyright      2020  Fangjun Kuang (csukuangfj@gmail.com)

# See ../../LICENSE for clarification regarding multiple authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# refer to https://github.com/actions/starter-workflows/pull/47/files

name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [labeled]

env:
  BUILD_TYPE: Release

jobs:
  build:
    if: github.event.label.name == 'ready' || github.event_name == 'push'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        # from https://download.pytorch.org/whl/torch_stable.html
        # Note: There are no torch versions for CUDA 11.2
        #
        # 1.11.x supports: cuda10.2 (default), 11.3, 11.5
        # 1.10.x supports: cuda10.2 (default), 11.1, 11.3
        # 1.9.x supports: cuda10.2 (default), 11.1
        # PyTorch 1.8.x supports: cuda 10.1, 10.2 (default), 11.1
        # PyTorch 1.7.x supports: cuda 10.1, 10.2 (default), 11.0
        # PyTorch 1.6.0 supports: cuda 10.1, 10.2 (default)
        # PyTorch 1.5.x supports: cuda 10.1, 10.2 (default)
        # Other PyTorch versions are not tested
        # CUDA 10.1 is for 1.5.x, 1.6.0, 1.7.x, 1.8.x
        # CUDA 11.1 is for torch 1.8.x, 1.9.x, 1.10.x
        # CUDA 11.3 is for torch 1.10, 1.11.x
        # CUDA 11.5 is for torch 1.11.x
        cuda: ["10.1", "10.2", "11.0", "11.1", "11.3", "11.5"]
        gcc: ["7"]
        torch: ["1.5.0", "1.5.1", "1.6.0", "1.7.0", "1.7.1", "1.8.0", "1.8.1", "1.9.0", "1.9.1", "1.10.0", "1.10.1", "1.10.2", "1.11.0"]
        #
        # torch 1.11.x does not support Python 3.6
        # From torch 1.11.x, it supports Python 3.10
        # Python 3.9 is for PyTorch 1.7.1, 1.8.0, 1.8.1, 1.9.x, 1.10.x, 11.x
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
        exclude:
          - cuda: "11.5" # exclude 11.3 for [1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2]
            torch: "1.5.0"
          - cuda: "11.5"
            torch: "1.5.1"
          - cuda: "11.5"
            torch: "1.6.0"
          - cuda: "11.5"
            torch: "1.7.0"
          - cuda: "11.5"
            torch: "1.7.1"
          - cuda: "11.5"
            torch: "1.8.0"
          - cuda: "11.5"
            torch: "1.8.1"
          - cuda: "11.5"
            torch: "1.9.0"
          - cuda: "11.5"
            torch: "1.9.1"
          - cuda: "11.5"
            torch: "1.10.0"
          - cuda: "11.5"
            torch: "1.10.1"
          - cuda: "11.5"
            torch: "1.10.2"
          - cuda: "11.3" # exclude 11.3 for [1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1]
            torch: "1.5.0"
          - cuda: "11.3"
            torch: "1.5.1"
          - cuda: "11.3"
            torch: "1.6.0"
          - cuda: "11.3"
            torch: "1.7.0"
          - cuda: "11.3"
            torch: "1.7.1"
          - cuda: "11.3"
            torch: "1.8.0"
          - cuda: "11.3"
            torch: "1.8.1"
          - cuda: "11.3"
            torch: "1.9.0"
          - cuda: "11.3"
            torch: "1.9.1"
          - cuda: "11.0" # exclude 11.0 for [1.5.0, 1.5.1, 1.6.0, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0]
            torch: "1.5.0"
          - cuda: "11.0"
            torch: "1.5.1"
          - cuda: "11.0"
            torch: "1.6.0"
          - cuda: "11.0"
            torch: "1.8.0"
          - cuda: "11.0"
            torch: "1.8.1"
          - cuda: "11.0"
            torch: "1.9.0"
          - cuda: "11.0"
            torch: "1.9.1"
          - cuda: "11.0"
            torch: "1.10.0"
          - cuda: "11.0"
            torch: "1.10.1"
          - cuda: "11.0"
            torch: "1.10.2"
          - cuda: "11.0"
            torch: "1.11.0"
          - cuda: "11.1" # exclude 11.1 for [1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.11.0]
            torch: "1.5.0"
          - cuda: "11.1"
            torch: "1.5.1"
          - cuda: "11.1"
            torch: "1.6.0"
          - cuda: "11.1"
            torch: "1.7.0"
          - cuda: "11.1"
            torch: "1.7.1"
          - cuda: "11.1"
            torch: "1.11.0"
          - cuda: "10.1" # exclude CUDA 10.1 for [1.9.0, 1.9.1, 1.10.0, 10.1, 10.2, 1.11.0]
            torch: "1.9.0"
          - cuda: "10.1"
            torch: "1.9.1"
          - cuda: "10.1"
            torch: "1.10.0"
          - cuda: "10.1"
            torch: "1.10.1"
          - cuda: "10.1"
            torch: "1.10.2"
          - cuda: "10.1"
            torch: "1.11.0"
          - python-version: 3.9 # exclude Python 3.9 for [1.5.0, 1.5.1, 1.6.0, 1.7.0]
            torch: "1.5.0"
          - python-version: 3.9
            torch: "1.5.1"
          - python-version: 3.9
            torch: "1.6.0"
          - python-version: 3.9
            torch: "1.7.0"
          - python-version: 3.10 # exclude Python 3.9 for [1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2]
            torch: "1.5.0"
          - python-version: 3.10
            torch: "1.5.1"
          - python-version: 3.10
            torch: "1.6.0"
          - python-version: 3.10
            torch: "1.7.0"
          - python-version: 3.10
            torch: "1.7.1"
          - python-version: 3.10
            torch: "1.8.0"
          - python-version: 3.10
            torch: "1.8.1"
          - python-version: 3.10
            torch: "1.9.0"
          - python-version: 3.10
            torch: "1.9.1"
          - python-version: 3.10
            torch: "1.10.0"
          - python-version: 3.10
            torch: "1.10.1"
          - python-version: 3.10
            torch: "1.10.2"
          - python-version: 3.6 # exclude Python 3.6 for [1.11.0]
            torch: "1.11.0"

    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Display date and time
        run: date

      - name: Install CUDA Toolkit ${{ matrix.cuda }}
        env:
          cuda: ${{ matrix.cuda }}
        run: |
          source ./scripts/github_actions/install_cuda.sh
          echo "CUDA_HOME=${CUDA_HOME}" >> $GITHUB_ENV
          echo "${CUDA_HOME}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${CUDA_HOME}/lib:${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        shell: bash

      - name: Display NVCC version
        run: |
          which nvcc
          nvcc --version

      - name: Install GCC ${{ matrix.gcc }}
        run: |
          sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
          echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV

      - name: Install git lfs
        run: |
          sudo apt-get install -y git-lfs

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install PyTorch ${{ matrix.torch }}
        env:
          cuda: ${{ matrix.cuda }}
          torch: ${{ matrix.torch }}
        shell: bash
        run: |
          python3 -m pip install -q --upgrade pip
          python3 -m pip install -q wheel twine typing_extensions
          python3 -m pip install -q bs4 requests tqdm

          ./scripts/github_actions/install_torch.sh
          python3 -c "import torch; print('torch version:', torch.__version__)"

      - name: Download cudnn 8.0
        env:
          cuda: ${{ matrix.cuda }}
        run: |
          ./scripts/github_actions/install_cudnn.sh

      - name: Configure CMake
        shell: bash
        run: |
          pwd
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
          cat k2/csrc/version.h

      - name: Build k2
        shell: bash
        run: |
          export K2_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=$BUILD_TYPE"
          export K2_MAKE_ARGS="-j2"
          python3 setup.py bdist_wheel
          ls -lh dist/
          ls -lh build/*

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: gcc-${{ matrix.gcc }}-cuda-${{ matrix.cuda }}-torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-${{ matrix.os }}
          path: dist/*.whl
