# Copyright (c)  2021  Xiaomi Corporation (authors: Fangjun Kuang)

name: Publish to PyPI - macOS CPU

on:
  push:
    tags:
      - '*'

concurrency:
  group: PyPI-macos-cpu-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  PyPI-macos-cpu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        torch: ["1.13.1"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install PyTorch ${{ matrix.torch }}
        shell: bash
        run: |
          python3 -m pip install -qq --upgrade pip
          python3 -m pip install -q wheel twine typing_extensions
          python3 -m pip install -qq torch==${{ matrix.torch }}


      - name: Build pip packages
        shell: bash
        env:
          K2_IS_FOR_PYPI: 1
          K2_IS_STABLE: 1
        run: |
          tag=$(python3 -c "import sys; print('.'.join(sys.version.split('.')[:2]))")
          export K2_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=$BUILD_TYPE"
          export K2_MAKE_ARGS="-j2"
          python3 setup.py bdist_wheel --python-tag=py${tag}
          ls -lh dist/

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-${{ matrix.os }}-cpu
          path: dist/*.whl

      - name: Publish wheels to PyPI
        if: ${{ github.repository_owner == 'k2-fsa' }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/k2-*.whl
